import { randomBytes } from 'node:crypto';
import { mkdir, readFile, readdir, rename, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { KeyedMutex } from '../async_lock.js';
import { IdenoError } from '../errors.js';
import { isCaseId } from '../ids.js';
import { summarizeState } from '../idea_state.js';
import { IdeaCaseSchema, SCHEMA_VERSION, type IdeaCase } from '../schemas.js';
import { validateCase, type CaseStore, type CaseSummary } from './store.js';

/**
 * Filesystem-backed case store: one JSON document per case.
 *
 * Chosen over a database because the Idea State is a single document per case
 * with no cross-case queries, the prototype is single-tenant, and a readable
 * on-disk format makes the "state is the product" claim inspectable. Writes
 * are atomic (temp file + rename) so a crash mid-write cannot truncate a case.
 */
export class FileCaseStore implements CaseStore {
  readonly #directory: string;
  readonly #mutex = new KeyedMutex();
  #ready: Promise<void> | null = null;

  constructor(directory: string) {
    this.#directory = directory;
  }

  async #ensureDirectory(): Promise<void> {
    this.#ready ??= mkdir(this.#directory, { recursive: true }).then(() => undefined);
    await this.#ready;
  }

  #pathFor(id: string): string {
    // Case ids are UUIDs generated by Ideno. Validating before touching the
    // filesystem keeps user-supplied ids from escaping the data directory.
    if (!isCaseId(id)) {
      throw new IdenoError('bad_request', `"${id}" is not a valid case id`);
    }
    return join(this.#directory, `${id}.json`);
  }

  async list(): Promise<CaseSummary[]> {
    await this.#ensureDirectory();
    const files = await readdir(this.#directory).catch(() => [] as string[]);
    const summaries: CaseSummary[] = [];

    for (const file of files) {
      if (!file.endsWith('.json')) continue;
      const id = file.slice(0, -'.json'.length);
      if (!isCaseId(id)) continue;
      const ideaCase = await this.#read(id).catch(() => null);
      if (!ideaCase) continue;
      const summary = summarizeState(ideaCase);
      summaries.push({
        id: ideaCase.id,
        title: ideaCase.title,
        created_at: ideaCase.created_at,
        updated_at: ideaCase.updated_at,
        version: summary.version,
        phase: ideaCase.current_state.phase,
        pending_changesets: summary.pendingChangeSets,
      });
    }

    summaries.sort((a, b) => b.updated_at.localeCompare(a.updated_at));
    return summaries;
  }

  async #read(id: string): Promise<IdeaCase | null> {
    await this.#ensureDirectory();
    let contents: string;
    try {
      contents = await readFile(this.#pathFor(id), 'utf8');
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') return null;
      throw new IdenoError('internal_error', `Unable to read case ${id}`, { cause: error });
    }

    let raw: unknown;
    try {
      raw = JSON.parse(contents);
    } catch (error) {
      throw new IdenoError('internal_error', `Case ${id} is not valid JSON on disk`, { cause: error });
    }

    const storedVersion = (raw as { schema_version?: unknown }).schema_version;
    if (storedVersion !== SCHEMA_VERSION) {
      throw new IdenoError(
        'internal_error',
        `Case ${id} uses schema version ${String(storedVersion)}; this build reads version ${SCHEMA_VERSION}`,
      );
    }

    const parsed = IdeaCaseSchema.safeParse(raw);
    if (!parsed.success) {
      throw new IdenoError('internal_error', `Case ${id} on disk does not match the current schema`, {
        details: parsed.error.issues.slice(0, 10),
      });
    }
    return parsed.data;
  }

  async get(id: string): Promise<IdeaCase | null> {
    return this.#read(id);
  }

  async #write(ideaCase: IdeaCase): Promise<void> {
    await this.#ensureDirectory();
    const target = this.#pathFor(ideaCase.id);
    const temporary = `${target}.${randomBytes(6).toString('hex')}.tmp`;
    const payload = `${JSON.stringify(ideaCase, null, 2)}\n`;
    try {
      await writeFile(temporary, payload, { encoding: 'utf8', mode: 0o600 });
      await rename(temporary, target);
    } catch (error) {
      await rm(temporary, { force: true }).catch(() => undefined);
      throw new IdenoError('internal_error', `Unable to persist case ${ideaCase.id}`, { cause: error });
    }
  }

  async create(ideaCase: IdeaCase): Promise<IdeaCase> {
    const validated = validateCase(ideaCase);
    return this.#mutex.run(validated.id, async () => {
      const existing = await this.#read(validated.id);
      if (existing) {
        throw new IdenoError('conflict', `Case ${validated.id} already exists`);
      }
      await this.#write(validated);
      return validated;
    });
  }

  async update(
    id: string,
    mutator: (ideaCase: IdeaCase) => Promise<IdeaCase> | IdeaCase,
  ): Promise<IdeaCase> {
    return this.#mutex.run(id, async () => {
      const current = await this.#read(id);
      if (!current) throw new IdenoError('not_found', `Case ${id} was not found`);
      const next = await mutator(current);
      if (next.id !== id) {
        throw new IdenoError('internal_error', 'A case mutator must not change the case id');
      }
      const validated = validateCase(next);
      await this.#write(validated);
      return validated;
    });
  }

  async delete(id: string): Promise<boolean> {
    return this.#mutex.run(id, async () => {
      const path = this.#pathFor(id);
      try {
        await rm(path);
        return true;
      } catch (error) {
        if ((error as NodeJS.ErrnoException).code === 'ENOENT') return false;
        throw new IdenoError('internal_error', `Unable to delete case ${id}`, { cause: error });
      }
    });
  }
}
